spring:
  application:
    name: fortune-cookie-rest
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/prod
    username: myuser
    password: mypassword
  flyway:
    user: myuser
    password: mypassword
    schemas: public
    #clean-on-validation-error: true
    #clean-disabled: false
    locations: classpath:/db/migration,classpath:/db/testdata