### Ping
GET {{serverUrl}}/ping

### Get fortunes
GET {{serverUrl}}/fortunes

### Get unique fortunes on author
GET {{serverUrl}}/fortunes/distinct

### Get orders
GET {{serverUrl}}/orders

### Add order
POST {{serverUrl}}/orders
Content-Type: application/json

{
  "fortuneId": 1
}

### Bake order
POST {{serverUrl}}/orders/1/bake
Content-Type: application/json

### Deliver order
POST {{serverUrl}}/orders/1/deliver
Content-Type: application/json

{
  "street": "Packhusplatsen 2",
  "postalCode": "411 13",
  "city": "Göteborg"
}